name: Monitor de Tasas Automatizado

on:
  schedule:
    # Se ejecuta de forma automática cada 2 horas
    - cron: '0 */2 * * *'
  workflow_dispatch: # Activa el botón manual en la pestaña Actions

permissions:
  contents: write

jobs:
  executar_robot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Inicializar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar Extractor de Precios
        run: python update_rates.py

      - name: Publicar cambios en el repositorio de forma segura
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Servidor actualizó tasas e historial automáticamente"
          branch: Principal
          file_pattern: 'rates.json historial.json'
