name: Monitor de Tasas Automatizado

on:
  workflow_dispatch:

jobs:
  update_rates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar Robot
        run: python update_rates.py

      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Actualizar tasas automáticamente" || echo "No hay cambios para subir"
          git push
